-- ============================================================
-- 0001_initial_schema.sql
-- Enums, tablas de catálogo (con seed), tablas core, índices y RLS.
-- ============================================================

-- ---------- Enums ----------
create type public.app_role as enum ('USER', 'ADMIN');
create type public.need_status as enum ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED');
create type public.help_offer_status as enum ('OFFERED', 'CONTACTED', 'AGREED', 'COMPLETED', 'CONFIRMED', 'CANCELLED');
create type public.image_kind as enum ('BEFORE', 'AFTER');
create type public.report_status as enum ('PENDING', 'REVIEWED', 'ACTIONED', 'DISMISSED');
create type public.report_reason as enum ('SUSPICIOUS', 'FALSE_INFO', 'SPAM', 'OFFENSIVE', 'FRAUD', 'MONEY_REQUEST', 'OTHER');
create type public.notification_type as enum ('HELP_OFFER', 'COMMENT', 'HELP_CONFIRMED', 'NEED_STATUS_CHANGE');

-- ---------- Catálogos ----------
create table public.municipalities (
  id smallint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique
);

create table public.capabilities (
  id smallint generated by default as identity primary key,
  slug text not null unique,
  label_es text not null
);

create table public.need_categories (
  id smallint generated by default as identity primary key,
  slug text not null unique,
  label_es text not null
);

-- ---------- Seed de catálogos ----------
insert into public.municipalities (slug, name) values
  ('pereira', 'Pereira'),
  ('dosquebradas', 'Dosquebradas');

insert into public.capabilities (slug, label_es) values
  ('request_help', 'Necesito ayuda'),
  ('labor', 'Mano de obra'),
  ('volunteer', 'Voluntariado'),
  ('materials', 'Materiales'),
  ('tools', 'Herramientas'),
  ('transport', 'Transporte'),
  ('advice', 'Asesoría / conocimientos'),
  ('other', 'Otra');

insert into public.need_categories (slug, label_es) values
  ('masonry', 'Albañilería'),
  ('home_repair', 'Reparación de vivienda'),
  ('roof', 'Techo'),
  ('electricity', 'Electricidad'),
  ('plumbing', 'Plomería'),
  ('waterproofing', 'Impermeabilización'),
  ('painting', 'Pintura'),
  ('debris_cleanup', 'Limpieza / retiro de escombros'),
  ('professional_assessment', 'Evaluación profesional'),
  ('other', 'Otra');

-- ---------- profiles ----------
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 80),
  municipality_id smallint references public.municipalities (id),
  bio text check (bio is null or char_length(bio) <= 500),
  app_role public.app_role not null default 'USER',
  banned_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index profiles_municipality_idx on public.profiles (municipality_id);
create index profiles_app_role_idx on public.profiles (app_role);

-- ---------- profile_capabilities ----------
create table public.profile_capabilities (
  profile_id uuid not null references public.profiles (id) on delete cascade,
  capability_id smallint not null references public.capabilities (id) on delete cascade,
  primary key (profile_id, capability_id)
);

-- ---------- profile_phone (privado) ----------
create table public.profile_phone (
  profile_id uuid primary key references public.profiles (id) on delete cascade,
  phone text not null check (char_length(phone) between 6 and 30),
  updated_at timestamptz not null default now()
);

-- ---------- needs ----------
create table public.needs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null check (char_length(title) between 5 and 120),
  description text not null check (char_length(description) between 20 and 4000),
  category_id smallint not null references public.need_categories (id),
  municipality_id smallint not null references public.municipalities (id),
  neighborhood text check (neighborhood is null or char_length(neighborhood) <= 120),
  status public.need_status not null default 'OPEN',
  needs_assessment boolean not null default false,
  is_hidden boolean not null default false,
  hidden_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index needs_status_created_idx on public.needs (status, created_at desc);
create index needs_municipality_idx on public.needs (municipality_id, status, created_at desc);
create index needs_category_idx on public.needs (category_id, status, created_at desc);
create index needs_user_idx on public.needs (user_id, created_at desc);

-- Regla de negocio: máximo una necesidad activa por usuario (atómica ante concurrencia)
create unique index one_active_need_per_user on public.needs (user_id)
  where status in ('OPEN', 'IN_PROGRESS');

-- ---------- need_address (privado) ----------
create table public.need_address (
  need_id uuid primary key references public.needs (id) on delete cascade,
  address text not null check (char_length(address) between 5 and 300),
  updated_at timestamptz not null default now()
);

-- ---------- need_images ----------
create table public.need_images (
  id uuid primary key default gen_random_uuid(),
  need_id uuid not null references public.needs (id) on delete cascade,
  storage_path text not null unique,
  kind public.image_kind not null default 'BEFORE',
  is_primary boolean not null default false,
  created_at timestamptz not null default now()
);

create index need_images_need_idx on public.need_images (need_id);
create unique index one_primary_image_per_need on public.need_images (need_id) where is_primary;

-- ---------- help_offers ----------
create table public.help_offers (
  id uuid primary key default gen_random_uuid(),
  need_id uuid not null references public.needs (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  capability_id smallint not null references public.capabilities (id),
  message text not null check (char_length(message) between 5 and 1000),
  status public.help_offer_status not null default 'OFFERED',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index help_offers_need_idx on public.help_offers (need_id, created_at);
create index help_offers_user_idx on public.help_offers (user_id, created_at desc);

-- Una oferta por persona por necesidad (re-ofrecer = UPDATE, no INSERT duplicado)
create unique index one_offer_per_user_per_need on public.help_offers (need_id, user_id)
  where status <> 'CANCELLED';

-- ---------- need_comments ----------
create table public.need_comments (
  id uuid primary key default gen_random_uuid(),
  need_id uuid not null references public.needs (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  body text not null check (char_length(body) between 2 and 2000),
  is_hidden boolean not null default false,
  hidden_at timestamptz,
  created_at timestamptz not null default now()
);

create index need_comments_need_idx on public.need_comments (need_id, created_at);

-- ---------- reports ----------
create table public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_id uuid not null references auth.users (id) on delete cascade,
  need_id uuid references public.needs (id) on delete set null,
  comment_id uuid references public.need_comments (id) on delete set null,
  reported_user_id uuid references auth.users (id) on delete set null,
  reason public.report_reason not null,
  details text check (details is null or char_length(details) <= 1000),
  status public.report_status not null default 'PENDING',
  moderated_by uuid references public.profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

-- Exactamente un objetivo reportable
alter table public.reports add constraint reports_exactly_one_target check (
  (need_id is not null)::int + (comment_id is not null)::int + (reported_user_id is not null)::int = 1
);

create index reports_status_created_idx on public.reports (status, created_at desc);
create index reports_need_idx on public.reports (need_id) where need_id is not null;
create index reports_comment_idx on public.reports (comment_id) where comment_id is not null;
create index reports_user_idx on public.reports (reported_user_id) where reported_user_id is not null;
create index reports_moderated_by_idx on public.reports (moderated_by);

-- Sin reportes duplicados del mismo autor sobre el mismo objetivo
create unique index one_report_per_user_target on public.reports (
  reporter_id,
  coalesce(need_id, '00000000-0000-0000-0000-000000000000'),
  coalesce(comment_id, '00000000-0000-0000-0000-000000000000'),
  coalesce(reported_user_id, '00000000-0000-0000-0000-000000000000')
);

-- ---------- contact_access_log ----------
create table public.contact_access_log (
  id uuid primary key default gen_random_uuid(),
  need_id uuid not null references public.needs (id) on delete cascade,
  viewer_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create index contact_access_log_need_idx on public.contact_access_log (need_id);

-- ---------- notifications ----------
create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  type public.notification_type not null,
  actor_id uuid references auth.users (id) on delete set null,
  need_id uuid references public.needs (id) on delete cascade,
  payload jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index notifications_user_idx on public.notifications (user_id, created_at desc);

-- ---------- RLS: habilitado desde el momento de creación (ARCH §47) ----------
alter table public.municipalities enable row level security;
alter table public.capabilities enable row level security;
alter table public.need_categories enable row level security;
alter table public.profiles enable row level security;
alter table public.profile_capabilities enable row level security;
alter table public.profile_phone enable row level security;
alter table public.needs enable row level security;
alter table public.need_address enable row level security;
alter table public.need_images enable row level security;
alter table public.help_offers enable row level security;
alter table public.need_comments enable row level security;
alter table public.reports enable row level security;
alter table public.contact_access_log enable row level security;
alter table public.notifications enable row level security;
